### ISSUE TITLE
Determine the link between the API and specifications

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-api#3]
#### Reason/Context
Now that we have a defined API we need to figure out the link between that API and specifications.

#### Description
I think it would be a great idea to dictate the link between the API and the specification so it is not up to the individual parsers to figure this out.

Take for example the [applicationPublishableChannels](https://github.com/asyncapi/parser-api/blob/master/docs/v1.md#asyncapidocument) function. Where should the parser find these channels?
The answer is it depends on the specification version. For `2.0.0` it is all `channels` that use the `subscribe` operation. But for imaginary version `3.0.0` it might be all `channels` that use the `publish` operation if that version changes to the perspective of the application.  We cannot possibly ask parser maintainers to know this.

Example API change:
```
- applicationPublishableChannels() : Channel[]
  - 2.0.0: all `channels` that use the `subscribe` operation
  ...
  - 3.0.0: all `channels` that use the `subscribe` operation
```

**Comment by smoya** [comment]
@jonaslagoni I'm reviving this topic as I want to invest some efforts in polishing the API so it is ready at some point for AsyncAPI spec v3.0.0.

As I understand, your proposal is to add some development guidelines around what the implementation should do, where should they grab the right info, etc.

Am I right?

**Comment by jonaslagoni** [comment]
> @jonaslagoni I'm reviving this topic as I want to invest some efforts in polishing the API so it is ready at some point for AsyncAPI spec v3.0.0.
> 
> As I understand, your proposal is to add some development guidelines around what the implementation should do, where should they grab the right info, etc.
> 
> Am I right?

Yep, that is right 👍 That way, JS, Go, Java and other parsers can easily know where to find the information 🙂

**Comment by smoya** [comment]
@jonaslagoni shall we keep this one opened for future API improvements?
