### ISSUE TITLE
Define how to handle unknown schema and message id's

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-api#34]
#### Reason/Context
Sometimes it happens that users do not define id for schemas and names for messages.

In the JS parser, we currently assign ids such as `anonymous-schema-x` and names `anonymous-message-x` where x is just a counter that increases for each found anonymous schema or message. There is another suggestion to switch to a more usable algorithm for naming them - https://github.com/asyncapi/parser-js/issues/176

#### Description
So how should be the algorithm that all parsers should implement?

**Comment by smoya** [comment]
Related somehow to this: https://github.com/asyncapi/parser-js/pull/453#issuecomment-1061534815
