### ISSUE TITLE
Clearly define how traits should be applied

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-api#36]
#### Reason/Context
Because traits can be somewhat hard to get right, we need to ensure that all parsers apply them correctly and provide all the necessary documentation to achieve it.

Related issues:
Spec issue: https://github.com/asyncapi/spec/issues/505
Spec PR: https://github.com/asyncapi/spec/pull/532

**Comment by Fannon** [comment]
Thanks for bringing this up!

In this JSFiddle I've provided two example implementations in JavaScript, in the case that we want to go with the approach proposed in [#532](https://github.com/asyncapi/spec/pull/532):
* https://jsfiddle.net/FannonF/yLsonr57/latest/

The first implementation (`function apply(origin, patch)`) is based on JSON Merge patch and deletes target properties if `null` is passed.

The second implementation (`function merge(...objects)`) is very similar, but skips on the special `null` behavior (my personal preference)

In general, I'm unsure whether we should base trait inheritance on the JSON Merge patch RFC, as its semantics are different from what we want to have from traits. Merge Path is basically about the patch overwriting the target. Inheritance / Traits are about applying information from the source to the target, but never overwriting the target.
I'm also unsure on the Merge Patch behavior of using `null` to remove a property. This is essential for patches, but I can see how this is misleading (and I think even unnecessary) for trait inheritance.

Please be aware that there are no unit-tests for this implementation. Before putting it into the spec, we should write unit-tests with various example data.
