### ISSUE TITLE
Detaching info and license object from spec structure

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/parser-api#43]
#### Describe the bug
I don't see any reason to have the [info object](https://github.com/asyncapi/parser-api/blob/master/docs/v1.md#info) as the better intents (and completely detached from the spec structure) would be something along the following lines:

I see these as pretty straightforward changes:
```
    document.contacts() : Contact[]
    document.description() : string | undefined
    document.id() : string | undefined
    document.tags() : Tag[] | undefined
    document.title() : string
    document.version() : string
    document.externalDocs() : ExternalDocument | undefined
    document.license() : License | undefined
    document.termsOfService() : string | undefined
    document.hasContacts() : boolean
    document.hasDescription() : boolean
    document.hasExternalDocs() : boolean
    document.hasId() : boolean
    document.hasTags() : boolean
    document.hasLicense() : boolean
    document.hasTermsOfService() : boolean
```

For extensions, it is quite different, and I am not sure how we should handle that. Maybe?
- informationHasExtension(name) : boolean (name : string)
- informationExtension(name) : any | undefined (name : string)

**Comment by fmvilas** [comment]
I think we have to think about who could be interested in reading the extensions and for what purpose. I can think of 2 use cases so far:

1. Tooling developers want to read an extension value to do something with it. E.g., React component shows the company logo placed under `info.x-logo`.
2. End-users read custom information they put on their AsyncAPI docs. E.g., They generate code and their business logic do X or Y depending on extension value.

Can you think of something else?

I think it should be fine to have `document.info(): Info` too, aside from the methods you already described. Maybe this Info object should contain these methods too or maybe not. I see benefits in both approaches. If we only offer the Info object with accessors to extension information, cool thing is that people will not have the temptation to do, e.g., `document.info().contacts()`. The bad part is that some will be lost thinking this info should be there, leading to bad DX. Trade-offs, trade-offs everywhere!
